import psycopg2
import sys

# DATABASE CREDENTIALS (URL Encoded Password)
DB_URL = "postgresql://postgres:%40Rusefx2026@db.lvlntilkvcmenzjyehng.supabase.co:5432/postgres"

SQL_COMMANDS = """
CREATE TABLE IF NOT EXISTS telemetry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  screen_id text,
  event_type text,
  version numeric
);

-- Reset RLS
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Allow public inserts" ON telemetry;
DROP POLICY IF EXISTS "Allow public reads" ON telemetry;

-- Create fresh policies
CREATE POLICY "Allow public inserts" ON telemetry FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public reads" ON telemetry FOR SELECT USING (true);
"""

def main():
    try:
        print("Connecting to Mr. Root Supabase Cluster...")
        conn = psycopg2.connect(DB_URL)
        cur = conn.cursor()
        
        print("Executing Schema Setup...")
        cur.execute(SQL_COMMANDS)
        conn.commit()
        
        cur.close()
        conn.close()
        print("SUCCESS: Telemetry table and RLS policies are now ACTIVE.")
    except Exception as e:
        print(f"ERROR: Database setup failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
